// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(express["static"]('doc'));

  app.use(express.directory('doc'));

  app.listen(3021);

}).call(this);
